# Generated by Django 4.1.5 on 2023-01-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='undone', max_length=6),
        ),
    ]
