# Generated by Django 4.1.5 on 2023-02-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_goal_status_minigoal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='percentage',
            field=models.CharField(default='0%', max_length=4),
        ),
    ]
